<div class="page-actions">
    <div class="page-actions-inner">
        <button class="action-primary" title="<?php echo __('Primary button'); ?>">
            <?php echo __('Primary button'); ?>
        </button>
        <button class="action-secondary" title="<?php echo __('Secondary button'); ?>">
            <?php echo __('Secondary button'); ?>
        </button>
        <button id="back" class="action- scalable back" title="<?php echo __('Back'); ?>">
            <?php echo __('Back'); ?>
        </button>
    </div>
</div>